REST:
    host: '0.0.0.0'
    port: 8000

model:
    variables: ['latitude',
                'longitude',
                'time_utc',
                'delta_time',
                'qa_value',
                'methane_mixing_ratio',
                'methane_mixing_ratio_precision',
                'methane_mixing_ratio_bias_corrected']
    timeVariable: 'time_utc'
    timeAggHours: 1
    readNameJSON: 'AidanData.json'
    writeNameJSON: 'AidanData.json'
    readJSON: True
    writeJSON: False 
    response: 'methane_mixing_ratio'

AnomalyDetector:
    windowSize: 1
    threshold: 0.5

logging:
    level: WARN
