REST:
    host: '0.0.0.0'
    port: 8000

model:
    prodVars: ['latitude',
               'longitude',
               'time',
               'time_utc',
               'qa_value',
               'methane_mixing_ratio',
               'methane_mixing_ratio_precision',
               'methane_mixing_ratio_bias_corrected']
    geoVars: ['solar_zenith_angle',
              'viewing_zenith_angle',
              'latitude_bounds',
              'longitude_bounds']
    detailedVars: ['water_total_column',
                   'surface_albedo_SWIR',
                   'surface_albedo_NIR',
                   'aerosol_optical_thickness_SWIR',
                   'aerosol_optical_thickness_NIR']
    inputVars: ['surface_altitude',
                'surface_altitude_precision',
                'surface_classification',
                'surface_pressure',
                'apparent_scene_pressure',
                'methane_weak_twoband_total_column',
                'methane_strong_twoband_total_column']
    regionName: 'ContiguousUSA'
    latLower: 25.0
    latUpper: 50.0
    lonLower: -125.0
    lonUpper: -67.0
    startDate: '2018-12-01'
    endDate: '2019-03-31'
    readh5File: True
    h5FileName: 'AidanData.h5'
    readRDataFile: False
    RDataFileName: 'AidanData.Rdata'
    RDataFrameName: 'AidanData'
    response: 'methane_mixing_ratio_bias_corrected'

AnomalyDetector:
    method: 'Local Outlier Factor'
    LocalOutlierFactorHyperparameters: {'spreadStatistic': 'IQR',
                                        'threshold': 1,
                                        'numNeighbors': 20,
                                        'algorithm': 'ball_tree',
                                        'leafSize': 30,
                                        'metric': 'manhattan',
                                        'p': 1}
    IsolationForestHyperparameters: {'spreadStatistic': 'IQR',
                                     'threshold': 1,
                                     'numEstimators': 100,
                                     'bootstrap': False}
    AutoencoderHyperparameters: {'inputNeurons': 50,
                                 'outputNeurons': 1,
                                 'depth': 5000,
                                 'hiddenLayerType': 'dense'}

logging:
    level: WARN
