REST:
    host: '0.0.0.0'
    port: 8000

model:
    variables: ['latitude',
                'longitude',
                'time_utc',
                'delta_time',
                'qa_value',
                'methane_mixing_ratio',
                'methane_mixing_ratio_precision',
                'methane_mixing_ratio_bias_corrected']
    timeVariable: 'time_utc'
    timeAggHours: 1

logging:
    level: WARN
